export type BookingItem = {
  id?: number;
  room_id: number;
  check_in: string;
  check_out: string;
  room_price: number;
  room_type_price?: number;
  num_adults: number;
  num_children: number;
  num_babies?: number;
  special_requests?: string;
  base_price?: number;
  extra_fees?: number;
  extra_adult_fees?: number;
  extra_child_fees?: number;
  extra_adults_count?: number;
  extra_children_count?: number;
  room_type_id?: number;
  room_type_name?: string;
  refund_amount?: number;
  status?: string;
  room_name?: string;
  receipt_image?: string;
  refund_status?: string;
  refund_request_id?: number;
  cancelled_at?: string;
  room_type_image?: string;
};
export interface BookingRoom {
  id: number;
  name: string;
  type_name: string;
  price: number;
  num_adults: number;
  num_children: number;
  num_babies?: number;
  extra_fees?: number;
  base_price?: number;
  extra_adult_fees?: number;
  extra_child_fees?: number;
  extra_adults_count?: number;
  extra_children_count?: number;
}
export type BookingService = {
  service_id: number;
  booking_item_id?: number;
  quantity: number;
  total_service_price: number;
};
export type Booking = {
  id?: number;
  customer_name: string;
  email?: string;
  phone?: string;
  notes?: string;
  total_price: number;
  total_room_price?: number;
  total_service_price?: number;
  cancel_reason?: string;
  canceled_by?: number;
  canceled_at?: string;
  canceled_by_name?: string;
  payment_status: string;
  payment_method?: string;
  booking_method: string;
  stay_status_id: number;
  user_id?: number;
  is_refunded?: boolean;
  change_count?: number;
  refund_amount?: number;
  original_total?: number;
  discount_amount?: number;
  discount_code?: string;
  discount_type?: string;
  discount_value?: number;
  promo_code?: string;
  items: BookingItem[];
  amount_paid?: number;
  services?: BookingService[];
  created_at?: string;
  stay_status_name?: string;
};
export type BookingShort = {
  id: number;
  customer_name: string;
  total_price: number;
  payment_status: string;
  stay_status_id: number;
  stay_status_name?: string;
  created_at?: string;
  is_refunded?: boolean;
};
export type BookingDetails = Booking & {
  check_in?: string;
  check_out?: string;
  total_room_price?: number;
  total_service_price?: number;
  cancel_reason?: string;
  canceled_by?: number;
  canceled_at?: string;
  status?: string;
  is_refunded?: boolean;
  checked_in_by_email?: string;
  checked_out_by_email?: string;
  canceled_by_email?: string;
  refund_amount?: number;
};
export type BookingUpdatePayload = {
  payment_status?: string;
  payment_method?: string;
  stay_status_id?: number;
  is_refunded?: boolean;
  notes?: string;
  total_price?: number;
  amount_paid?: number;
};
